### PR TITLE
LPS-106486 Update bootstrap collapse usages to new native one

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
@john-co could you please take a look. This is part of the jquery-removal epic and could be potentially risky. This pr involves multiple teams modules so we should check it with them. Thx!

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
Thanks @carloslancha, I will analyze the ci test results and do some manual checks. Will notify other QA members.

**Comment by john-co** [comment]
**Reviewed. Test failures are unrelated**. :heavy_check_mark: 

[Comparison Details](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=932898051&testrayRunIdA=934506515&statusB=2)
Unique functional test failures look like flukes.

**Comment by john-co** [comment]
Not critical for GA1, please hold off merging until GA1 is released since we're under a stabilization period.

**Pull request closed without merging**
