### PR TITLE
LPS-107942 We don't use AUI.$ anymore, so use CollapseProvider instead

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by carloslancha** [comment]
Hey @markocikos looks like we leave one usage of AUI.$ on a collapsible node. Also we discovered a couple of `Liferay.CollapseProvider.show` usages that are not following the API (sending an object with the panel), and the `getTrigger` method not appending `#` to the selector.

Could you please take a look? If it looks good to you just let me know to fwd the pr to Bchan. Thanks!

**Comment by markocikos** [comment]
@carloslancha Looks good to me!

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
sent here: https://github.com/brianchandotcom/liferay-portal/pull/84173

**Pull request closed without merging**
