### PR TITLE
LPS-75371 Simple Input Modal

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by jpince** [comment]
@p2kmgcl I think your changes breaks Web Content. I think there are other test failures as well, but this is the most significant.
```
     [exec] 15:03:14,974 ERROR [http-nio-8080-exec-4][PortletRequestDispatcherImpl:265] Unable to dispatch request: com.liferay.portal.kernel.template.TemplateException: Unable to process templates
     [exec] 15:03:14,977 ERROR [http-nio-8080-exec-4][PortletServlet:112] javax.portlet.PortletException: javax.servlet.ServletException: com.liferay.portal.kernel.template.TemplateException: Unable to process templates
     [exec] javax.portlet.PortletException: javax.servlet.ServletException: com.liferay.portal.kernel.template.TemplateException: Unable to process templates
     [exec] 	at com.liferay.portlet.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:267)
     [exec] 	at com.liferay.portlet.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:102)
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:594)
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:610)
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:494)
     [exec] 	at com.liferay.journal.web.internal.portlet.JournalPortlet.doDispatch(JournalPortlet.java:1230)
```
image
https://testray.liferay.com/reports/production/logs/test-1-18/1511359169377/test-portal-acceptance-pullrequest(master)/2860/functional-tomcat80-mysql56-jdk8/39/0/jenkins-console.txt.gz

**Comment by p2kmgcl** [comment]
@jpince I will have a look

**Comment by p2kmgcl** [comment]
@jpince thanks, there was a problem with the indentation.
@carloslancha done :smile:

**Comment by p2kmgcl** [comment]
ci:retest

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:retest

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:retest

**Pull request closed without merging**
