### PR TITLE
LPS-95726 Disable jQuery by default | v2

### PR DESCRIPTION
**Pull request by markocikos**
Hey @carloslancha @john-co

This is a followup on https://github.com/carloslancha/liferay-portal/pull/240, with added commits for portal-workflow-metrics-web modal.

A note on added commits: modal that now uses ClayModal instead of custom html is functional, but it still does not have ideal behavior. It should have the the async loading pattern, as for example in [SingleReassignModal](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/portal-workflow/portal-workflow-metrics-web/src/main/resources/META-INF/resources/js/components/instance-list-page/modal/single-reassign/SingleReassignModal.es.js). Tests should be rewritten to match.

/cc @jbalsas

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
Hey @markocikos if I followed correctly how that module is composed, they're instantiating the App on the `view.jsp` file in this way:

```
<aui:script require='<%= npmResolvedPackageName + " as bootstrapRequire" %>'>
	bootstrapRequire.default(
		<%= PropsValues.SEARCH_CONTAINER_PAGE_DEFAULT_DELTA %>,
		<%= Arrays.toString(PropsValues.SEARCH_CONTAINER_PAGE_DELTA_VALUES) %>,
		<%= DateUtil.isFormatAmPm(locale) %>,
		<%= PropsValues.SEARCH_CONTAINER_PAGE_ITERATOR_MAX_PAGES %>,
		'<portlet:namespace />'
	);
</aui:script>
```

This is (being polite) not the best way of doing it, we have the tag `react:component` to do it. Among other things, doing it in that way the component will receive some params and context like `spritemap` and `namespace`, so it's available and there's no need of hardcode thinks like

```
Liferay.ThemeDisplay.getPathThemeImages() + '/lexicon/icons.svg';
```

You can take a look at how we use `react:component` use a `Context.Provider` to have some data available through all the app in [this example](https://github.com/liferay/liferay-portal/blob/9d9fde2b59f8d50feed7ccd01519dbd8edf064a9/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/view.jsp#L331) and try to implement it if possible.

**Comment by markocikos** [comment]
@carloslancha The entry point of react app is [here](https://github.com/liferay/liferay-portal/blob/9d9fde2b59f8d50feed7ccd01519dbd8edf064a9/modules/dxp/apps/portal-workflow/portal-workflow-metrics-web/src/main/resources/META-INF/resources/js/index.es.js#L23). `view.jsp` only serves to place root container node, there is no way to insert `<react:component>` beyond. I can only follow existing structure, unless we want to refactor entire module. Even if we do, that's beyond the scope of this task.

**Comment by carloslancha** [comment]
@markocikos the react app entry point is that, yes, but that is being initialized via the `view.jsp` `<aui:script>` code I referred before.  That part can be replaced with `react:component`.

In that way you will be receiving automatically that params (`spritemap` and stuff). In addition to that a `Context.Provider` could be added just to not pass those "global" all the way through the components. It shouldn't require more refactor than that and, agreeing about that is out of the scope of the task, it's a good moment to try to get rid of that way of initializing react components, which we don't want to happen anyware.

**Comment by markocikos** [comment]
@carloslancha I see what you mean, that makes sense! I'll followup with the change.

**Pull request closed without merging**
