### PR TITLE
LPS-105711 Remove ajax from Liferay.Service

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
@john-co could you please take a deep look into this? It's a risky change, we're moving the jquery ajax config and removing jquery from our JSON WS client (Liferay.Service).

Thanks!

**Comment by tainguyen100** [comment]
ci:test:bundle

**Comment by tainguyen100** [comment]
The failures don't appear to have been caused by the PR.

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Running full suite test to see if anything else pops up

**Comment by jbalsas** [comment]
Hey @john-co, @tainguyen100, can you also check the full `ci:test` run to see if anything stands out? If it all looks okay, please, feel free to push it forward!

Thanks!

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
**Reviewed. Test failures are unrelated.** :heavy_check_mark: 

**Comparison:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=932898051&testrayRunIdA=934035206&statusB=2
The following had passed previous `ci test relevant` run:
TagsUseCase#ViewTagCloudIncrease
FragmentsImporter#ExportImportCollectionViewFragment
DisplayPagesWithWebContent#ViewDisplayPageViaAssetPublisher

All other test failures look flaky, especially WorkflowCalendar#ApproveEventWithInvitedUser

Will perform a manual exploratory test on `ci test bundle`, will push to BChan if looks ok.

**Comment by jbalsas** [comment]
Great, thanks @john-co!

**Comment by john-co** [comment]
Passed Manual Testing on Chrome 78 and IE11

Pushed to BChan
master: https://github.com/brianchandotcom/liferay-portal/pull/82621

**Comment by john-co** [comment]
ci:close

**Pull request closed without merging**
