### PR TITLE
LPS-105924 Remove jquery from focusFormField

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
@john-co could you please take a look. This is part of the jquery-removal epic and could be potentially risky. Thx!

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
At a brief glance, the tests are not able to sign in. The form field is not editable.
[PortalSmoke#Smoke](https://testray.liferay.com/reports/production/logs/test-1-8/1577986630970/test-portal-acceptance-pullrequest(master)/4581/functional-smoke-tomcat90-mysql57-jdk11_open/0/0/LocalFile.PortalSmoke_Smoke/index.html.gz)

image

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by john-co** [comment]
**Reviewed. Test failures are unrelated.** :heavy_check_mark: 

[Comparison Details](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=936330275&testrayRunIdA=936684546&statusB=2)

Unique test failures most likely caused by a sync issue with SitePages.gotoAddFirstPage macro https://issues.liferay.com/browse/LRQA-54813

**Comment by carloslancha** [comment]
ci:test:relevant

**Pull request closed without merging**
