### PR TITLE
LPS-64308 - SF

### PR DESCRIPTION
**Pull request by Robert-Frampton**
Hey @carloslancha @ealonso 

I made some small formatting changes to the metal components to more closely match the patterns we've been following in other metal components.

I also noticed a few issues, can you guys take a look and resend?

1) The toggleDisableInputs component doesn't work in IE/Edge
2) Occasionally the Close button on the look and feel modal doesn't close the modal (not sure if this was already issue before these changes, if so please ignore).

### CODE REVIEW

**Comment by carloslancha** [comment]
LGTM, thanks @Robert-Frampton  !

**Comment by carloslancha** [comment]
I'll take a look on the issues on monday and I'll resend ;)

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
@Robert-Frampton Hi! When you say "ocassionally"... how can I reproduce it? :sweat_smile:

**Comment by Robert-Frampton** [comment]
Hey @carloslancha 

Sorry I don't have this branch built anymore so I can't test right now, but from what I remember it was always after changing various colors inputs in the look and feel modal.

**Comment by carloslancha** [comment]
Pull request submitted to https://github.com/Robert-Frampton/liferay-portal/pull/375. [See changes here.](https://github.com/carloslancha/liferay-portal/compare/77df579~1...77df579) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Pull request submitted to https://github.com/carloslancha/liferay-portal/pull/92. [See changes here.](https://github.com/carloslancha/liferay-portal/compare/13d1cf3~1...13d1cf3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Pull request submitted to https://github.com/Robert-Frampton/liferay-portal/pull/376. [See changes here.](https://github.com/carloslancha/liferay-portal/compare/13d1cf3~1...13d1cf3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
