### PR TITLE
LPS-94658 Using ckeditor in conjunction with alloyeditor mixes events and do not handle images correctly

### PR DESCRIPTION
**Pull request by almonwork**

### CODE REVIEW

**Comment by almonwork** [comment]
Hi @carloslancha 

After debugging (thanks @antonio-ortega), we realized that, in this function, event refers to another editor that the editor variable.

This fix is more a hack than a solution, as it does not address the root cause about why different editors are mixing events. Could there be a different approach?

Regards
  Alberto

**Comment by almonwork** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
@julien

**Comment by julien** [comment]
Just started reviewing :)

**Comment by almonwork** [comment]
Hi,

We just realized that it works in 7.0 (thanks @robertoDiaz)

Regards

**Comment by julien** [comment]
thanks @almonwork and @robertoDiaz 👍

**Pull request closed without merging**
