### PR TITLE
LPS-100110 Standardize Ajax requests in portal-web

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
LGTM!

**Comment by carloslancha** [comment]
ci:test:sg

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77643. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
