### PR TITLE
LPS-105934 | Remove jQuery from selectEntityHandler

### PR DESCRIPTION
**Pull request by markocikos**
Hey @carloslancha ,

Couple of notes with this one:
- I moved the solution to `Liferay.provide` because it requires `A.one()`. `A` is not available otherwise. We require an AUI node for `A.delegate()`
- I reworked the disabled check, adding check for `currentTarget.disabled` and changing check for `data-prevent-selection` from `target` to `currentTarget`. The reason for this is jQuery has different behavior from YUI when it comes to delegation over disabled elements. YUI triggers event if the child node of disabled element is clicked, while jQuery does not. This is why jQuery solution worked: it would never reach the code that was meant to cover this scenario in AUI. After I changed it, it became apparent that `target` is incorrect, as it referred to child element, a `<span>` in the button. I am guessing this behavior is the reason why `data-prevent-selection` exists, as it was unnecessary under jQuery. If this data attribute is set in backend, everything is fine. But, somebody using util after it became jQuery could have relied only on disabling; for this reason I added explicit check for `currentTarget.disabled`.

Please review and merge to frontend-js-aui-web jQuery removal solution.

Thank you!

/cc @jbalsas

### CODE REVIEW

**Comment by carloslancha** [comment]
Hey @markocikos 

A is not available? I just added `A.one('body') in the original `selectEntityHandler` method and it worked.

**Comment by markocikos** [comment]
@carloslancha I couldn't test `toggleSearchContainerButton`, it is unused. Having this in mind, that solution would not work. I'm guessing that without Liferay.provide it is a race condition of what gets loaded first.

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
