### PR TITLE
LPS-95726 Disable jQuery by default

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Hey @john-co we put together on this pr all task left in jquery-removal epic, including the three of them you already reviewed (https://github.com/carloslancha/liferay-portal/pull/228 https://github.com/carloslancha/liferay-portal/pull/229 https://github.com/carloslancha/liferay-portal/pull/226).

Could you please take a look to the test results to see if the failures are really related? Thanks!

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
- portal-workflow-metrics-web js-unit snapshot tests need to be updated due to new dropdown utility usage `liferay-dropdown`

- I will need to investigate further the error observed in site page creation modal
Error: ```Please enter a unique name```, it could be caused by previous failing tests in the same instance. See if reproducible in next ci test run
-- [StagingUsecaseWithRoles#StagingPublishPage](https://testray.liferay.com/home/-/testray/case_results/952191295)
-- [SiteTeams#EditSiteTeam](https://testray.liferay.com/home/-/testray/case_results/952198259)

**Comment by john-co** [comment]
Comparison
Mostly flaky tests or flukes: 
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=7&testrayRunIdB=950839622&testrayRunIdA=952170222&statusB=2

marked as flaky
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=950839622&testrayRunIdA=952170222&statusB=2

**Pull request closed without merging**
