### PR TITLE
[TECHNICAL-SUPPORT] LPS-69279 Performance problem with checking or unchecking all pages

### PR DESCRIPTION
**Pull request by moltam89**
Hi @carloslancha , @zxdgoal,

I saw that you were working on [LPS-67718](https://issues.liferay.com/browse/LPS-67718) which modified the same file, could you please review my changes?

Let me know if I should send this pr to someone else.

Thanks,
Tamás

### CODE REVIEW

**Comment by moltam89** [comment]
ci:retest

**Comment by moltam89** [comment]
Hi @carloslancha , @zxdgoal,

do you have any update?

I can't see the connection between the failing tests and my fix.

Thanks,
Tamás

**Comment by carloslancha** [comment]
Hey @moltam89 I don't know so much about this, I only did a small SF on the js files of the other ticket. Maybe @zxdgoal can help you. Sorry!

**Comment by zxdgoal** [comment]
I think the change is fine.

The change I made generated some redundant codes.

And there should be no change in functionalities in this pr.

Thanks
@moltam89

**Comment by moltam89** [comment]
Thanks!

I forwarded it to https://github.com/juliocamarero/liferay-portal/pull/4312.

**Pull request closed without merging**
