### PR TITLE
LPS-114108 | LPS-114108-Global-Apps-Transitions

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-114108

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
I'm adding this commit to the original commit, let's pass the test battery there ;)

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Added on https://github.com/wincent/liferay-portal/pull/321

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
ci:stop

**Pull request closed without merging**
