### PR TITLE
LPS-99160 Localize string

### PR DESCRIPTION
**Pull request by JavierMoral**
Hi,
I send this pull to fix [https://issues.liferay.com/browse/LPS-99160](https://issues.liferay.com/browse/LPS-99160), could you please take a look at it?
/cc @antonio-ortega
Thanks!

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76506. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
