### PR TITLE
LPS-115388 Replace logo and name with real ones

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
@john-co could you please take a look at this? Some global menu markup has changed so maybe we need to update some poshi tests, but don't know if failures here are related. Thx!

**Comment by john-co** [comment]
Hi @carloslancha , upstream is affected by a lcs kernal version dependency issue. Please see https://liferay.slack.com/archives/CLCD3DQLF/p1592247756212200

It's being looked into. Probably need to rerun tests after the fix.

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
@ealonso could you please review the java part of this commit? https://github.com/carloslancha/liferay-portal/pull/271/commits/01747bbe9c985187f1bf53b3450a872c1bf528d5

Thx!

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/1096

**Pull request closed without merging**
