### PR TITLE
LPS-125413 | master

### PR DESCRIPTION
**Pull request by nikki-pru**
https://issues.liferay.com/browse/LPS-125413

Fix for https://github.com/liferay-lima/liferay-portal/pull/1494#issuecomment-778168684

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:reopen

**Comment by carloslancha** [comment]
Thx @nikki-pru !!

**Comment by carloslancha** [comment]
Added to https://github.com/liferay-lima/liferay-portal/pull/1494

**Pull request closed without merging**
