### PR TITLE
LPS-74679

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @ealonso

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:reopen

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/23. [See changes here.](https://github.com/carloslancha/liferay-portal/compare/82e1de09deb4~2...82e1de09deb4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/24. [See changes here.](https://github.com/carloslancha/liferay-portal/compare/e468fe4cdfee~3...e468fe4cdfee) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
