### PR TITLE
LPS-83968 Displaying the right default value

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by izaera** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
Pull request submitted to https://github.com/boton/liferay-portal/pull/17

This is exactly the same as https://github.com/carloslancha/liferay-portal/pull/174 so I guess that one can be closed too.

**Comment by 4lejandrito** [comment]
Latest and shiniest: https://github.com/ambrinchaudhary/liferay-portal/pull/181.

**Pull request closed without merging**
