### PR TITLE
LPS-95726 Disable jQuery by default | v5

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
cc @markocikos

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test:bundle

**Comment by carloslancha** [comment]
ci:test

**Comment by carloslancha** [comment]
@john-co this is the last  pr with all the jquery-removal-related epic stuff. Could you please review if failures are related? Thx!

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Hi @carloslancha, the js-unit snapshot failures look related:
https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/318542/#showFailuresLink

functional test failures are unrelated.

**Comment by carloslancha** [comment]
Thx @john-co ! I'll take a look and let you know when fixed to final confirmation before sending it to Bchan :)

**Comment by carloslancha** [comment]
ci:test:stable

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test

**Comment by john-co** [comment]
Hi @carloslancha, looks like there's some other lingering js-unit tests still failing.

It might be related to: https://issues.liferay.com/browse/LPS-107319

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:stop

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test

**Comment by carloslancha** [comment]
@john-co I think js-unit are fixed now. I the other failures are unrelated we should be good to go now. Let me know when you have a minute. Thx!!

**Comment by john-co** [comment]
@carloslancha looks good! :heavy_check_mark: 

**Comparison Details:**
functional tests:
https://testray.liferay.com/home/-/testray/runs/compare?formDate=1579542186675&testrayRunIdA=963109005&testrayRunIdB=962966467

**Pull request closed without merging**
