### PR TITLE
LPS-105922 - Do not use jQuery

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
/cc @jbalsas

@john-co could you please take a look. This is part of the jquery-removal epic and could be potentially risky. Thx!

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
**Reviewed `ci test relevant` results. Test failures are unrelated.** :heavy_check_mark:

[Comparison Details](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=932898051&testrayRunIdA=934513452&statusB=2)
Unique Test failures look like flukes.

**Comment by john-co** [comment]
**Reviewed. Test failures are unrelated.** :heavy_check_mark: 

[Comparison Details](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=934940010&testrayRunIdA=934938854&statusB=2)
Unique test failures look like flukes.

**Pull request closed without merging**
