### PR TITLE
OAUTH2-165

### PR DESCRIPTION
**Pull request by topolik**
Hi Carlos,

can you please review the CSS? 

That's the discussion you had with @stian-sigvartsen about OAuth2 edit screen having pencil icon below input box.

Thanks.

/cc @stian-sigvartsen

### CODE REVIEW

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
LGTM, but i found something strange:

http://recordit.co/hjqPZUML2N

**Comment by stian-sigvartsen** [comment]
Hey @carloslancha , yes these are other known issues: [OAUTH2-154](https://issues.liferay.com/browse/OAUTH2-154), [OAUTH2-152](https://issues.liferay.com/browse/OAUTH2-152)

Also there is a modal scrolling issue which I suspect is related to the off-center rendering issue. [OAUTH2-162](https://issues.liferay.com/browse/OAUTH2-162)

We haven't classified these as release blockers, but definitely something we need to resolve soon. Your insight of course is valuable if you have the time 👍

**Comment by carloslancha** [comment]
@stian-sigvartsen I'll let you know if we can take a look. For now resend this pr to Brian. Thx!

**Comment by stian-sigvartsen** [comment]
Thanks @carloslancha . See https://github.com/brianchandotcom/liferay-portal/pull/60709

**Pull request closed without merging**
