### PR TITLE
LPS-70628 scroll into view of opened web content in asset publisher

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46678. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
